import streamlit as st
import numpy as np
from wordcloud import WordCloud
import matplotlib.pyplot as plt
from main import keyword_extraction_text_rank

st.title("Welcome to WordCloud!")
st.text("Put your text here and generate your word cloud! (Note: You may want to put two or more sentences or more than 20 words to generate the simplest word cloud.)")
user_input = st.text_area("text goes here")

if st.button('generate word cloud'):
    if not user_input:
        st.text("Oops, word cloud cannot be generated by empty input.")
    else:
        extracted_key_words, frequency_dict = keyword_extraction_text_rank(user_input)
        word_cloud = WordCloud(width = 800, height = 800, background_color ='white', min_font_size = 10).generate_from_frequencies(frequency_dict)
        fig, ax = plt.subplots()
        ax.imshow(word_cloud)
        ax.axis('off')
        st.pyplot(fig)
